### ISSUE TITLE
统一的交叉引用命名格式

### ISSUE THREAD

**Issue by jianiwuoo** [OpenHUTB/PFC#131]
因书籍的章节之间具有连贯性，为防止出现引用时的编译错误，建议大家统一采用刘家琪同学一开始使用的引用命名格式：
章节命名格式：例第一章——\label{chap:chap1}
图片命名格式：例图2.1——\label{fig:fig_2_1}
表格命名格式：例表3.1——\label{tab:tab_3_1}

**Comment by AwooDancer** [comment]
收到收到
