### ISSUE TITLE
链接显示出来了

### ISSUE THREAD

**Issue by donghaiwang** [OpenHUTB/PFC#167]
超链接一般隐藏起来，可以参考别人写的。
另外每个人需要选两章进行翻译 和 两章进行校验。 @lulu7795  @12oneway

**Comment by donghaiwang** [comment]
@perfectwlx

**Comment by lulu7795** [comment]
老师我这边看到的是超链接形式啊

**Comment by donghaiwang** [comment]
> 老师我这边看到的是超链接形式啊

已经修复了
